// Code generated by hertztool. DO NOT EDIT.

package round_robin_service

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	handler "github.com/DexMus/round_robin_service/biz/handler"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {}
func RoundRegister(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_game_center := _api.Group("/game_center", _game_centerMw()...)
			{
				_v1 := _game_center.Group("/v1", _v1Mw()...)
				{
					_meta := _v1.Group("/meta", _metaMw()...)
					{
						_round_query := _meta.Group("/round_query", _round_queryMw()...)
						_round_query.POST("/", append(_roundquerygameinfoMw(), handler.RoundQueryGameInfo)...)
					}
				}
			}
		}
	}
}

func SimpleRegister(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_game_center := _api.Group("/game_center", _game_centerMw()...)
			{
				_v1 := _game_center.Group("/v1", _v1Mw()...)
				{
					_meta := _v1.Group("/meta", _metaMw()...)
					{
						_query := _meta.Group("/query", _queryMw()...)
						_query.POST("/", append(_querygameinfoMw(), handler.QueryGameInfo)...)
					}
				}
			}
		}
	}
}