Develop:
  ServicePort: "6789"
  DebugPort: "6799"
  EnablePprof: true
  LogLevel: "debug"
  ConsoleLog: true
  AgentLog: true
  FileLog: true

Product:
  ServicePort: "6789"
  DebugPort: "6791"
  EnablePprof: true
  LogLevel: "info"
  ConsoleLog: false
  AgentLog: true
  FileLog: true