// Code generated by hertztool. DO NOT EDIT.

package router

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	github_DexMus_round_robin_service "github.com/DexMus/round_robin_service/biz/router/github/DexMus/round_robin_service"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	github_DexMus_round_robin_service.Register(r)
}
